steps:
  - id: generate-terraform-creds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ['gcloud', 'iam', 'service-accounts', 'keys', 'create', '${PROJECT_ID}.json', '--iam-account', 'terraform@${PROJECT_ID}.iam.gserviceaccount.com']
  - id: terraform-formatting
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['fmt', '-recursive', '-check']
  - id: terraform-init
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['init']
  - id: terraform-validate
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['validate', '.']
  - id: terraform-plan
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['plan', '-out', 'tf.plan']
  - id: terraform-apply
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['apply', 'tf.plan']
  - id: gsutil-copy
    name: gcr.io/marwan01-terraform-admin/gsutil
    entrypoint: gsutil
    args: ['cp', 'index.html', 'gs://website-bucket-11242021/index.html']