steps:
  - id: terraform-formatting
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['fmt', '-recursive', '-check']
  - id: terraform-init
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['init']
  - id: terraform-validate
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['validate', '.']
  - id: terraform-plan
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['plan', '-out', 'tf.plan']
  - id: terraform-apply
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['apply', 'tf.plan']
  - id: gsutil-copy
    name: gcr.io/marwan01-terraform-admin/gsutil
    entrypoint: gsutil
    args: ['cp', 'index.html', 'gs://website-bucket-11242021/index.html']
  - id: gsutil-public-permission
    name: gcr.io/marwan01-terraform-admin/gsutil
    entrypoint: gsutil
    args: ['iam', 'ch', 'allUsers:objectViewer', 'gs://website-bucket-11242021/index.html']