steps:
  - id: terraform-formatting
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['fmt', '-recursive', '-check']
  - id: terraform-init
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['init']
  - id: terraform-validate
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['validate', '.']
  - id: terraform-plan
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['plan', '-out', 'tf.plan', '-lock=false']
  - id: terraform-apply
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['apply', '-out', 'tf.plan']
  - id: gsutil copy
    name: gcr.io/marwan01-terraform-admin/gsutil
    entrypoint: gsutil
    args:
      - -c
      - |
        gsutil cp index.html gs://website-bucket-11242021/index.html
        gsutil iam ch allUsers:objectViewer gs://website-bucket-11242021/index.html
tags: ["terraform"]