steps:
  - id: terraform-formatting
    name: gcr.io/marwan01-terraform-admin/terraform:0.14.3
    entrypoint: bash
    args:
      - -c
      - |
        echo "Unformatted files (if any):"
        terraform fmt -recursive -check
  - id: terraform-validate
    name: gcr.io/marwan01-terraform-admin/terraform:0.14.3
    entrypoint: bash
    args:
      - -c
      - |
        terraform init
        terraform validate
  - id: terraform-plan
    name: gcr.io/marwan01-terraform-admin/terraform:0.14.3
    entrypoint: bash
    args:
      - -c
      - |
        terraform plan -out tf.plan
  - id: terraform-apply
    name: gcr.io/marwan01-terraform-admin/terraform:0.14.3
    entrypoint: bash
    args:
      - -c
      - |
        terraform apply tf.plan
tags: ["terraform", "validation"]