steps:
  # use gcloud iam command to pull a copy of the terraform service acct creds
  - id: generate-terraform-creds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ['gcloud', 'iam', 'service-accounts', 'keys', 'create', '${PROJECT_ID}.json', '--iam-account', 'terraform@${PROJECT_ID}.iam.gserviceaccount.com']
  # build and tag image of our golang API
  - id: build app
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'us-west2-docker.pkg.dev/go-automated-infra/go-automated-infra-repo/go-automated-infra', '.']
  # push golang API built image to artifact registry
  - id: push artifact
    name: gcr.io/cloud-builders/docker
    args: ['push', 'us-west2-docker.pkg.dev/go-automated-infra/go-automated-infra-repo/go-automated-infra']
  # error out and print unformatted terraform code
  - id: terraform-formatting
    name: us-west2-docker.pkg.dev/${PROJECT_ID}/go-automated-infra-repo/terraform:latest
    args: ['fmt', '-recursive', '-check']
  # initialize the terraform backend
  - id: terraform-init
    name: us-west2-docker.pkg.dev/${PROJECT_ID}/go-automated-infra-repo/terraform:latest
    args: ['init']
  # error out and print invalid syntax
  - id: terraform-validate
    name: us-west2-docker.pkg.dev/${PROJECT_ID}/go-automated-infra-repo/terraform:latest
    args: ['validate', '.']
  # create the terraform plan and output it to tf.plan
  - id: terraform-plan
    name: us-west2-docker.pkg.dev/${PROJECT_ID}/go-automated-infra-repo/terraform:latest
    args: ['plan', '-out', 'tf.plan']