steps:
  # use gcloud iam command to pull a copy of the terraform service acct creds
  - id: generate-terraform-creds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ['gcloud', 'iam', 'service-accounts', 'keys', 'create', '${PROJECT_ID}.json', '--iam-account', 'terraform@${PROJECT_ID}.iam.gserviceaccount.com']
  # error out and print unformatted terraform code
  - id: terraform-formatting
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['fmt', '-recursive', '-check']
  # initialize the terraform backend
  - id: terraform-init
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['init']
  # error out and print invalid syntax
  - id: terraform-validate
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['validate', '.']
  # create the terraform plan and output it to tf.plan
  - id: terraform-plan
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['plan', '-out', 'tf.plan']
  # CAREFUL: apply the terraform plan in tf.plan to create the desired infrastructure
  - id: terraform-apply
    name: gcr.io/marwan01-terraform-admin/terraform
    args: ['apply', 'tf.plan']
  # copy content of public to the created GCS bucket
  - id: gsutil-copy
    name: gcr.io/marwan01-terraform-admin/gsutil
    entrypoint: gsutil
    args: ['cp', 'index.html', 'gs://website-bucket-11242021/index.html']