project_id         = "go-automated-infra"
region             = "us-west4"
bucket_name        = "website-bucket-12072021"
static_site_source = "public/index.html"
bq_table_name         = "my-table"
bq_instance_name      = "my-instance-id"